# -*- coding: utf-8 -*-
"""hw103

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NKZ_DImaTBFjC7D5N7jI3zVfedhfwakR
"""

from google.colab import files
data = files.upload()

import pandas as pd
import plotly.express as px
df = pd.read_csv('Copy+of+data+-+data (1).csv')

fig = px.line(df, x= "date", y = "cases" , color = "country" )
fig.show()